### ISSUE TITLE
expand to this to have belongsTo

### ISSUE THREAD

**Issue by ken-muturi** [michalsn/codeigniter-nested-model#1]
Thanks for this cool trait. Its quite awesome.  Now, how can i expand this to include a belongsTo?

**Comment by michalsn** [comment]
It should work now however, you must use `hasOne` and declare the `local key` and `foreign key` manually.

```php
// AvatarModel.php
protected $relations = [
    // one user - relation type, model, foreign key, local key
    'user' => ['hasOne', UserModel::class, 'id', 'user_id'],
];
```

**Comment by ken-muturi** [comment]
Thanks,  yeah i reviewed the code and its just inverting the pk vs fk.   

How would you advise to nest this down;  Project has many Interventions, which belongs to InterventionTypes. 

Am struggling on the controller with 

`$projects = $this->projectModel->with("interventions")->with('interventionType');
`

 Incorrect relation name: interventionType

**Comment by michalsn** [comment]
Try this or similar. It should work if you have declared a correct relation in the `InterventionModel`.
```php
$projects = $this->projectModel->with("interventions", static function () {
    model(InterventionModel::class)->with('interventionType');
}); 
```

**Comment by michalsn** [comment]
Please, remember that this project is just an experiment.

**Comment by ken-muturi** [comment]
thanks, yes i am just trying to learn ci4 with all the goodies it brings. I could use illuminate model for the ORM. but good to learn how this extension would work
